default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vulnerability_development

test:
  <<: *default
  database: vulnerability_test

production:
  <<: *default
  database: vulnerability_production
  username: vulnerability
  password: <%= ENV['VUL_DATABASE_PASSWORD'] %>